"""
Test suite for all Python code, some of which is generated by atdpy.

Each function starting with 'test_' is executed as a test by pytest.
"""

import manual_sample


def test_sample():
    a_str = '{"id": "hello"}'
    a_obj = manual_sample.Sample.from_json_string(a_str)
    a_str2 = a_obj.to_json_string()

    b_obj = manual_sample.Sample("hello")
    b_str = b_obj.to_json_string()

    assert a_str == a_str2  # depends on json formatting (whitespace...)
    assert a_str2 == b_str


def test_sample_missing_field():
    try:
        manual_sample.Sample.from_json_string('{}')
        assert False
    except ValueError:
        pass


def test_sample_wrong_type():
    try:
        manual_sample.Sample.from_json_string('["hello"]')
        assert False
    except ValueError:
        pass


def test_hello():
    assert True
