(** Runtime library for code generated by atdml. *)

(** {1 Primitive type converters} *)

val bool_of_yojson : Yojson.Safe.t -> bool
val yojson_of_bool : bool -> Yojson.Safe.t

val int_of_yojson : Yojson.Safe.t -> int
val yojson_of_int : int -> Yojson.Safe.t

val float_of_yojson : Yojson.Safe.t -> float
val yojson_of_float : float -> Yojson.Safe.t

val string_of_yojson : Yojson.Safe.t -> string
val yojson_of_string : string -> Yojson.Safe.t

val unit_of_yojson : Yojson.Safe.t -> unit
val yojson_of_unit : unit -> Yojson.Safe.t

(** {1 Compound type converters} *)

val list_of_yojson : (Yojson.Safe.t -> 'a) -> Yojson.Safe.t -> 'a list
val yojson_of_list : ('a -> Yojson.Safe.t) -> 'a list -> Yojson.Safe.t

(** ATD [option] type: JSON [null] or ["None"] encodes [None];
    JSON [["Some", x]] encodes [Some x]. *)
val option_of_yojson : (Yojson.Safe.t -> 'a) -> Yojson.Safe.t -> 'a option
val yojson_of_option : ('a -> Yojson.Safe.t) -> 'a option -> Yojson.Safe.t

(** ATD [nullable] type: JSON [null] encodes [None];
    any other JSON value [x] encodes [Some x]. *)
val nullable_of_yojson : (Yojson.Safe.t -> 'a) -> Yojson.Safe.t -> 'a option
val yojson_of_nullable : ('a -> Yojson.Safe.t) -> 'a option -> Yojson.Safe.t

(** {1 Error helpers} *)

val bad_type : string -> Yojson.Safe.t -> 'a
(** [bad_type expected_type json] raises a [Failure] exception describing
    that [json] has an unexpected type. *)

val bad_sum : string -> Yojson.Safe.t -> 'a
(** [bad_sum type_name json] raises a [Failure] exception describing
    an invalid variant for the given sum type. *)

val missing_field : string -> string -> 'a
(** [missing_field type_name field_name] raises a [Failure] exception
    describing a missing required field. *)
